### ISSUE TITLE
next js support ?

### ISSUE THREAD

**Issue by BinarySenseiii** [Julien-Marcou/Scrollable-Component#5]
m getting this error in next js  document is not defined
![image](https://user-images.githubusercontent.com/68985954/207530886-cb6fa4f8-4e4d-4f0b-ae50-cb4eeef69922.png)

**Comment by adrsr** [comment]
Hello, because of server-side rendering enabled by default with Next.js , you don't have access to the document object when the component is first rendered on the server. That is why you get this error : *document is not defined*

You can use Next's dynamic import : https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

code example :
```javascript
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(
  () => import('scrollable-component'),
  { ssr: false }
)
```

**Comment by Julien-Marcou** [comment]
While disabling server-side rendering is a valid option, I don't necessarily recommend it.

For a better user experience, I would prefer to import the `scrollable-component` script directly on the client side, because that's how it's supposed to be used.

Here is the documentation on [how to import a third-party script globally for your application](https://nextjs.org/docs/basic-features/script#application-scripts).

This way it won't have to be lazy loaded and therefore will make the `<scrollable-component>` and its content directly accessible (better for SEO and accessibility).

To be able to import the `scrollable-component` script, you will have to use a custom Webpack Config and a Webpack Plugin to copy the file.

---

First install the `copy-webpack-plugin` plugin:

`npm install --save-dev copy-webpack-plugin`

Then, create a Webpack Config (`next.config.js`) similar to this one:

```js
const CopyPlugin = require('copy-webpack-plugin');

const nextConfig = {
  webpack: (config) => {
    config.plugins.push(new CopyPlugin({
      patterns: [
        {
          from: './node_modules/scrollable-component/index.js',
          to: './static/scrollable-component.js',
        },
      ],
    }))

    return config
  },
}

module.exports = nextConfig

```

In your `pages/_app.js`, do something like this:

```jsx
import Script from 'next/script'

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Script src="/_next/static/scrollable-component.js" type="module" />
      <Component {...pageProps} />
    </>
  )
}
```

And finally use the `scrollable-component` wherever you want:

```jsx
export default function Home() {
  return (
    <scrollable-component scrollbar-visibility="always" style={{height: '400px', width: '600px', border: '3px solid red'}}>
      <div style={{height: '1000px', background: 'linear-gradient(to bottom, blue, red)'}}></div>
    </scrollable-component>
  )
}
```

**Comment by Julien-Marcou** [comment]
However, if you still wanna go with the lazy loading solution proposed by @adrsr, I found a neat trick that works a little bit better than wrapping the `scrollable-component` inside a lazy loaded React Component.

The idea is to create a fake React Component that do nothing but import the `scrollable-component`.

That way the content of the `<scrollable-component>` is also directly available (better for SEO and accessibility) before the lazy loading of the script happens.

But I still don't necessarily recommend this solution, as it involves a bit of "magic" to understand the logic behind, and find it less scalable than the Webpack Config.

---

In your `pages/_app.js`, do something like this:

```jsx
import dynamic from 'next/dynamic'

const LazyLoadScrollableComponentScript = dynamic(
  async () => {
    await import('scrollable-component')
    return () => {}
  },
  { ssr: false },
)

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <LazyLoadScrollableComponentScript />
      <Component {...pageProps} />
    </>
  )
}
```

Then you can use the `scrollable-component` wherever you want:

```jsx
export default function Home() {
  return (
    <scrollable-component scrollbar-visibility="always" style={{height: '400px', width: '600px', border: '3px solid red'}}>
      <div style={{height: '1000px', background: 'linear-gradient(to bottom, blue, red)'}}></div>
    </scrollable-component>
  )
}
```
